Repository boostcamp-2020/Project16-F-Account-Book, pull requests merged in 2020-11, with the labels that each got.

#5 chore : pull request template added
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#7 chore : updated pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#6 chore : server init
  server/.gitignore
  server/nodemon.json
  server/package.json
  server/src/index.ts
  server/tsconfig.json
Labels: backend, chore

#28 master -> dev
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .github/workflows/auto_reviewer.yml
  README.md
Labels: chore

#29 chore : project eslint 설정
  .prettierrc
  .vscode/settings.json
  client/.eslintrc.json
  client/package.json
  client/src/index.tsx
  client/src/reportWebVitals.ts
  server/.eslintrc.json
  server/package.json
  server/src/index.ts
  yarn.lock
Labels: chore

#31 Precommit hook 설정
  client/package.json
  package.json
  server/package.json
  yarn.lock
Labels: chore

#32 fix: auto_assign.yml 리뷰어 목록 수정
  .github/auto_assign.yml
Labels: chore

#30 chore : template mention 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/issue------.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#33 [feature] database entity 정의
  .gitignore
  server/.dummy.env
  server/package.json
  server/src/entity/category.entity.ts
  server/src/entity/fixedExpenditure.entity.ts
  server/src/entity/payment.entity.ts
  server/src/entity/transaction.entity.ts
  server/src/entity/user.entity.ts
  server/src/index.ts
  server/src/loader/database.ts
  server/src/loader/index.ts
Labels: backend, database, feature

#34 Path alias 설정 추가
  client/config-overrides.js
  client/package.json
  client/tsconfig.json
  client/tsconfig.paths.json
  server/nodemon.json
  server/package.json
  server/tsconfig.json
  yarn.lock
Labels: chore

#35 auth 폴더구조 추가
  server/package.json
  server/src/auth/auth.router.ts
  server/src/auth/auth.service.ts
  server/src/auth/types/.gitkeep
  server/src/loader/index.ts
  server/src/loader/router.ts
Labels: chore

#39 JWT 토큰 발급, 인증기능 구현
  server/package.json
  server/src/auth/auth.service.ts
  server/src/auth/types/.gitkeep
  server/src/auth/types/decodedJWT.ts
  server/src/auth/types/userDTO.ts
Labels: feature

#40 kakao OAuth 구현
  server/.dummy.env
  server/package.json
  server/src/auth/auth.router.ts
  server/src/auth/auth.service.ts
  server/src/auth/types/decoded-jwt.ts
  server/src/auth/types/kakao-user-info.ts
  server/src/auth/types/social-user-dto.ts
  server/src/auth/types/user-dto.ts
  server/src/common/error.ts
  server/src/user/types/user.ts
  server/src/user/user.service.ts
Labels: backend, feature

#42 naver OAuth 구현
  server/src/auth/auth.router.ts
  server/src/auth/auth.service.ts
  server/src/auth/types/kakao-user-dto.ts
  server/src/auth/types/kakao-user-info.ts
  server/src/auth/types/naver-user-dto.ts
  server/src/auth/types/social-user-dto.ts
  server/src/user/user.service.ts
Labels: backend, feature

#44 더미데이터 생성을 위한 seeder 구현
  server/.dummy.env
  server/package.json
  server/src/entity/category.entity.ts
  server/src/entity/payment.entity.ts
  server/src/entity/transaction.entity.ts
  server/src/entity/user.entity.ts
  server/src/loader/database.ts
  server/src/seed/clear.ts
  server/src/seed/generateSeedData.ts
  server/src/seed/up.ts
Labels: backend, database, feature

#45 feat:클라이언트 디렉토리설정
  client/src/commons/actions/.gitkeep
  client/src/commons/hooks/.gitkeep
  client/src/components/category/.gitkeep
  client/src/components/common/.gitkeep
  client/src/components/common/buttons/OAuthLoginButton/buttonResourceFactory.ts
  client/src/components/common/buttons/OAuthLoginButton/index.stories.tsx
  client/src/components/common/buttons/OAuthLoginButton/index.tsx
  client/src/components/common/buttons/OAuthLoginButton/styles/default.ts
  client/src/components/common/buttons/OAuthLoginButton/styles/google.ts
  client/src/components/common/buttons/OAuthLoginButton/styles/kakao.ts
  client/src/components/common/buttons/OAuthLoginButton/styles/naver.ts
  client/src/container/calendar/.gitkeep
  client/src/view/.gitkeep
  yarn.lock
Labels: chore, frontend

#49 로고 컴포넌트 구현
  client/src/components/Logo/index.stories.tsx
  client/src/components/Logo/index.tsx
  client/src/components/Logo/style.ts
  client/src/components/Logo/types.ts
Labels: feature, frontend

#48 feat : css 초기화 및 router 설정
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/view/.gitkeep
  client/src/views/dashBoard.tsx
Labels: frontend

#51 리액트 컴포넌트의 반환 타입 수정
  client/src/components/Logo/index.tsx
  client/src/components/common/buttons/OAuthLoginButton/index.tsx
Labels: frontend

#50 Google OAuth 구현, 로그인 확인 API 구현
  server/src/auth/auth.router.ts
  server/src/auth/auth.service.ts
  server/src/auth/types/google-user-dto.ts
  server/src/middleware/jwt-authorize.ts
  server/src/middleware/types/decoded-jwt.ts
  server/src/user/user.service.ts
Labels: backend, feature

#54 로그인 페이지 구현
  .gitignore
  client/package.json
  client/src/App.tsx
  client/src/container/loginButton/index.tsx
  client/src/container/loginButton/style.ts
  client/src/views/login/index.tsx
  client/src/views/login/style.ts
  server/package.json
  server/src/auth/auth.router.ts
  server/src/index.ts
Labels: feature, frontend

#53 Server의 lint-staged 가 동작하지 않던 이슈 해결
  server/package.json
Labels: backend, bug, chore

#59 DB 테이블 네이밍 전략 수정, Seeder 모듈 리팩토링
  server/src/config/orm/snake-naming-strategy.ts
  server/src/seed/seed-generator.ts
  server/src/seed/test.seed.ts
  server/src/seed/up.ts
Labels: backend, database, refactoring

#57 modal layout 구현
  client/src/App.tsx
  client/src/components/common/.gitkeep
  client/src/components/common/buttons/commonButton/index.tsx
  client/src/components/common/buttons/commonButton/style.tsx
  client/src/components/common/buttons/commonButton/types.tsx
  client/src/components/transaction/modal/index.tsx
  client/src/components/transaction/modal/style.tsx
  client/src/components/transaction/modalHeaderText/index.tsx
  client/src/components/transaction/modalHeaderText/style.tsx
  client/src/components/transaction/modalHeaderText/types.tsx
  client/src/components/transaction/modalInput/index.stories.tsx
  client/src/components/transaction/modalInput/index.tsx
  client/src/components/transaction/modalInput/style.tsx
  client/src/components/transaction/modalInput/types.ts
  client/src/components/transaction/modalRadioButton/index.tsx
  client/src/components/transaction/modalRadioButton/style.tsx
  client/src/components/transaction/modalXButton/index.tsx
  client/src/components/transaction/modalXButton/style.tsx
  client/src/components/transaction/modalXButton/types.tsx
  client/src/container/TransactionModal/index.stories.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionModal/style.tsx
  client/src/container/TransactionModal/types.ts
Labels: feature, frontend

#62 고정 지출 API 구현
  server/src/auth/auth.router.ts
  server/src/entity/fixed-expenditure.entity.ts
  server/src/entity/user.entity.ts
  server/src/fixedExpenditure/fixed-expenditure.router.ts
  server/src/fixedExpenditure/fixed-expenditure.ts
  server/src/loader/router.ts
  server/src/middleware/jwt-authorize.ts
Labels: backend, feature

#60 월 가계부 내역 API 구현
  .gitignore
  package.json
  server/jest.config.js
  server/package.json
  server/src/config/orm/index.ts
  server/src/loader/index.ts
  server/src/loader/router.ts
  server/src/transaction/transaction.repository.ts
  server/src/transaction/transaction.router.ts
  server/src/transaction/transaction.service.test.ts
  server/src/transaction/transaction.service.ts
  server/src/transaction/types.ts
  server/tsconfig.json
  yarn.lock
Labels: backend, feature

#65 OAuth 리팩토링 진행
  server/.dummy.env
  server/package.json
  server/src/auth/auth.router.ts
  server/src/auth/auth.service.ts
  server/src/auth/oauth-client/index.ts
  server/src/auth/types/decoded-jwt.ts
  server/src/auth/types/naver-user-dto.ts
  server/src/auth/utils/jwt-utils.ts
  server/src/config/index.ts
  server/src/config/orm/index.ts
  server/src/loader/database.ts
  server/src/loader/router.ts
  server/src/middleware/jwt-authorize.ts
  server/tsconfig.json
  yarn.lock
Labels: backend, refactoring

#64 금액표시 컴포넌트 구현
  client/.storybook/main.js
  client/package.json
  client/src/components/transaction/AmountText/index.stories.tsx
  client/src/components/transaction/AmountText/index.tsx
  client/src/components/transaction/AmountText/styles.ts
  client/src/components/transaction/AmountText/types.ts
  client/src/libs/numberUtils.ts
  client/tsconfig.paths.json
  package.json
  yarn.lock
Labels: feature, frontend

#72 backend 리팩토링
  server/src/auth/auth.router.ts
  server/src/domain/auth/auth.router.ts
  server/src/domain/auth/types/decoded-jwt.ts
  server/src/domain/auth/types/google-user-dto.ts
  server/src/domain/auth/types/kakao-user-dto.ts
  server/src/domain/auth/types/naver-user-dto.ts
  server/src/domain/auth/types/social-user-dto.ts
  server/src/domain/auth/types/user-dto.ts
  server/src/domain/auth/utils/jwt-utils.ts
  server/src/domain/category/.gitkeep
  server/src/domain/fixed-expenditure/fixed-expenditure.repository.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.router.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
  server/src/domain/fixed-expenditure/types.ts
  server/src/domain/payment/.gitkeep
  server/src/domain/transaction/transaction.repository.ts
  server/src/domain/transaction/transaction.router.ts
  server/src/domain/transaction/transaction.service.test.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/domain/transaction/types.ts
  server/src/domain/user/types/user.ts
  server/src/domain/user/user.repository.ts
  server/src/domain/user/user.service.ts
  server/src/fixedExpenditure/fixed-expenditure.router.ts
  server/src/fixedExpenditure/fixed-expenditure.ts
  server/src/lib/oauth-client/index.ts
  server/src/loader/router.ts
  server/src/middleware/jwt-authorize.ts
  server/src/user/user.service.ts
Labels: backend, refactoring

#68 modal Toggle Button 구현
  client/src/components/common/buttons/modalToggleButton/index.tsx
  client/src/components/common/buttons/modalToggleButton/style.tsx
  client/src/components/common/buttons/modalToggleButton/types.tsx
Labels: feature, frontend

#61 Feature/header
  client/src/components/Dropdown/index.tsx
  client/src/components/Dropdown/style.ts
  client/src/components/Dropdown/types.ts
  client/src/components/Logo/style.ts
  client/src/components/User/index.tsx
  client/src/components/User/style.ts
  client/src/components/User/types.ts
  client/src/components/common/typeComponent/Link/index.tsx
  client/src/components/common/typeComponent/Link/types.ts
  client/src/components/header/icons.tsx
  client/src/components/header/index.tsx
  client/src/components/header/style.ts
  client/src/container/Dropdown/index.tsx
  client/src/container/Dropdown/style.ts
  client/src/container/Dropdown/types.ts
  client/src/views/dashBoard.tsx
  client/tsconfig.paths.json
Labels: feature, frontend

#74 카테고리 API 구현
  server/package.json
  server/src/domain/category/.gitkeep
  server/src/domain/category/category.repository.ts
  server/src/domain/category/category.router.ts
  server/src/domain/category/category.service.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.repository.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.router.ts
  server/src/domain/transaction/transaction.router.ts
  server/src/index.ts
  server/src/loader/router.ts
Labels: backend, feature

#78 탭 UI 컴포넌트 구현
  client/src/components/common/Logo/index.stories.tsx
  client/src/components/common/Logo/index.tsx
  client/src/components/common/Logo/style.ts
  client/src/components/common/Logo/types.ts
  client/src/components/common/TabMenu/index.stories.tsx
  client/src/components/common/TabMenu/index.tsx
  client/src/components/common/TabMenu/styles.ts
  client/src/components/common/TabMenu/types.ts
  client/src/container/loginButton/index.tsx
  client/src/views/login/index.tsx
  client/tsconfig.paths.json
Labels: feature, frontend

#80 거래내역 create, update, delete API 구현
  server/src/domain/transaction/transaction.router.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/domain/transaction/types.ts
Labels: backend, feature
