Repository boostcamp-2020/Project16-F-Account-Book, pull requests merged in 2020-12, with the labels that each got.

#96 dropdown 위치조절 기능 추가 & 폴더구조변경 & dropdown list 생성방식 변경
  client/src/components/common/Dropdown/index.tsx
  client/src/components/common/Dropdown/style.ts
  client/src/components/common/Dropdown/types.ts
  client/src/components/common/Header/index.stories.tsx
  client/src/components/common/Header/index.tsx
  client/src/components/common/Header/style.ts
  client/src/components/common/Link/index.tsx
  client/src/components/common/Link/types.ts
  client/src/components/common/li/index.tsx
  client/src/components/common/li/style.ts
  client/src/components/common/li/types.ts
  client/src/views/DashBoardPage/index.tsx
Labels: feature, frontend

#91 Feature/Arrow 컴포넌트 구현
  client/src/App.tsx
  client/src/assets/svg/arrow.svg
  client/src/components/common/Arrow/index.stories.tsx
  client/src/components/common/Arrow/index.tsx
  client/src/components/common/Arrow/style.ts
  client/src/components/common/Arrow/types.ts
  client/src/views/Calendar/index.tsx
Labels: feature, frontend

#93 모달 결제수단 가져오기 구현
  client/package.json
  client/src/commons/hooks/.gitkeep
  client/src/commons/types/payment.ts
  client/src/components/common/buttons/commonButton/style.tsx
  client/src/components/transaction/ModalSelectInput/index.tsx
  client/src/components/transaction/ModalSelectInput/style.tsx
  client/src/components/transaction/ModalSelectInput/types.ts
  client/src/components/transaction/modal/style.tsx
  client/src/components/transaction/modalInput/style.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/index.tsx
  client/src/libs/api/payment.ts
  client/src/modules/index.ts
  client/src/modules/payment/actions.ts
  client/src/modules/payment/index.ts
  client/src/modules/payment/reducer.ts
  client/src/modules/payment/thunks.ts
  client/src/modules/payment/types.ts
  client/src/views/dashBoard/index.tsx
  client/tsconfig.paths.json
  yarn.lock
Labels: feature, frontend

#95 카테고리 별 통계, 최대값 API 구현
  server/src/domain/aggregate/aggregate.router.ts
  server/src/domain/aggregate/aggregate.service.ts
  server/src/domain/aggregate/types.ts
  server/src/loader/router.ts
Labels: backend, feature

#98 trasaction modal user 카테고리 가져오기 구현
  client/src/commons/types/category.ts
  client/src/container/TransactionModal/index.tsx
  client/src/libs/api/category.ts
  client/src/libs/createAsyncThunk.ts
  client/src/modules/category/actions.ts
  client/src/modules/category/index.ts
  client/src/modules/category/reducer.ts
  client/src/modules/category/thunks.ts
  client/src/modules/category/types.ts
  client/src/modules/index.ts
  client/src/modules/payment/actions.ts
  client/src/modules/payment/thunks.ts
  client/src/views/dashBoard/index.tsx
Labels: feature, frontend

#106 modal radio button 작동 및 transaction module 추가
  client/src/commons/types/transaction.ts
  client/src/components/common/Modal/index.tsx
  client/src/components/common/Modal/types.ts
  client/src/components/transaction/ModalRadioButton/index.tsx
  client/src/components/transaction/ModalRadioButton/types.ts
  client/src/container/TransactionModal/index.tsx
  client/src/libs/api/transaction.ts
  client/src/modules/index.ts
  client/src/modules/transaction/actions.ts
  client/src/modules/transaction/index.ts
  client/src/modules/transaction/reducer.ts
  client/src/modules/transaction/thunks.ts
  client/src/modules/transaction/types.ts
Labels: feature, frontend

#105 Header를 갖는 MainLayout 컴포넌트 구현
  client/src/components/common/layouts/Header/index.stories.tsx
  client/src/components/common/layouts/Header/index.tsx
  client/src/components/common/layouts/Header/styles.ts
  client/src/components/common/layouts/MainLayout/index.tsx
  client/src/components/common/layouts/MainLayout/styles.ts
  client/src/components/common/layouts/MainLayout/types.ts
Labels: feature, frontend

#110 transaction 상태관리 수정 및 모달 동작 수정
  client/public/index.html
  client/src/App.tsx
  client/src/commons/dto/category.ts
  client/src/commons/dto/payment.ts
  client/src/commons/dto/transaction-request.ts
  client/src/commons/types/category.ts
  client/src/commons/types/payment.ts
  client/src/commons/types/transaction.ts
  client/src/components/common/forms/CustomInput/index.tsx
  client/src/components/common/forms/CustomInput/types.ts
  client/src/components/common/forms/CustomSelectInput/index.tsx
  client/src/components/common/forms/CustomSelectInput/types.ts
  client/src/components/transaction/ModalRadioButton/index.tsx
  client/src/components/transaction/ModalRadioButton/types.ts
  client/src/container/TransactionModal/index.tsx
  client/src/libs/api/transaction.ts
  client/src/libs/createAsyncThunk.ts
  client/src/modules/index.ts
  client/src/modules/transaction/actions.ts
  client/src/modules/transaction/aggregateUtil.ts
  client/src/modules/transaction/reducer.ts
  client/src/modules/transaction/types.ts
  client/src/views/Calendar/index.tsx
  client/src/views/DashBoardPage/index.tsx
  client/tsconfig.json
  server/src/domain/transaction/transaction.service.test.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/domain/transaction/types.ts
Labels: feature, frontend

#113 Dashboard 내역 컨테이너 구현
  client/src/GlobalStyled.ts
  client/src/components/common/layouts/Header/styles.ts
  client/src/components/common/layouts/MainLayout/styles.ts
  client/src/components/transaction/ListItem/index.stories.tsx
  client/src/components/transaction/ListItem/index.tsx
  client/src/components/transaction/ListItem/styles.ts
  client/src/components/transaction/ListItem/types.ts
  client/src/container/DashboardDetails/index.tsx
  client/src/container/DashboardDetails/styles.ts
  client/src/container/DashboardMain/index.tsx
  client/src/libs/api/transaction.ts
  client/src/modules/transaction/actions.ts
  client/src/modules/transaction/reducer.ts
  client/src/modules/transaction/thunks.ts
  client/src/modules/transaction/types.ts
  client/src/views/DashBoardPage/index.tsx
  server/src/domain/transaction/transaction.service.test.ts
  yarn.lock
Labels: feature, frontend

#112 로그인 인증 버그 수정, 고정 지출 상태 관리
  client/src/App.tsx
  client/src/commons/types/fixedExpenditure.ts
  client/src/container/Authorization/index.tsx
  client/src/container/FixedExpenditure/index.tsx
  client/src/libs/api/Authorization.ts
  client/src/libs/api/fixedExpenditure.ts
  client/src/libs/dateUtils.ts
  client/src/modules/fixedExpenditure/actions.ts
  client/src/modules/fixedExpenditure/index.ts
  client/src/modules/fixedExpenditure/reducer.ts
  client/src/modules/fixedExpenditure/thunks.ts
  client/src/modules/fixedExpenditure/types.ts
  client/src/modules/index.ts
  client/src/views/LoginPage/index.tsx
  server/src/domain/fixed-expenditure/fixed-expenditure.router.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
Labels: backend, feature, frontend

#120 배포를 위한 Docker 스크립트 작성 및 CI/CD workflow 추가
  .github/workflows/deploy.yml
  .github/workflows/pre-release.yml
  .github/workflows/run-test.yml
  client/Dockerfile
  client/src/libs/endpoints.ts
  client/src/modules/index.ts
  docker-compose.build.yml
  docker-compose.dev.yml
  nginx.dev.conf
  package.json
  scripts/build.sh
  server/.dummy.env
  server/Dockerfile
  server/package.json
  server/src/config/index.ts
  server/src/domain/auth/auth.router.ts
  server/src/domain/auth/types/google-user-dto.ts
  server/src/domain/auth/types/kakao-user-dto.ts
  server/src/domain/auth/types/naver-user-dto.ts
  server/src/domain/auth/types/social-user-dto.ts
  server/src/domain/user/user.service.ts
  server/src/index.ts
  server/src/lib/oauth-client/index.ts
  server/src/lib/oauth-client/userinfo/default.ts
  server/src/lib/oauth-client/userinfo/factory.ts
  server/src/lib/oauth-client/userinfo/google.ts
  server/src/lib/oauth-client/userinfo/kakao.ts
  server/src/lib/oauth-client/userinfo/naver.ts
  server/tsconfig.json
Labels: backend, chore

#121 날짜별로 묶어서 보여주는 List 컨테이너 구현 및 가계부 내역 순서 조정
  client/src/container/Calendar/index.tsx
  client/src/container/Calendar/styles.ts
  client/src/container/TransactionList/index.tsx
  client/src/container/TransactionList/styles.ts
  client/src/modules/transaction/reducer.ts
  server/.dummy.env
  server/src/domain/transaction/transaction.service.ts
  yarn.lock
Labels: backend, feature, frontend, refactoring

#125 rechart 를 활용한 linegraph 컴포넌트 구현
  client/package.json
  client/src/components/transaction/LineGraph/index.tsx
  client/src/components/transaction/LineGraph/styles.tsx
  client/src/components/transaction/LineGraph/types.ts
  client/src/container/LineGraphContainer/index.tsx
  client/src/container/LineGraphContainer/style.tsx
  client/src/container/LineGraphContainer/types.tsx
  client/src/libs/dateUtils.ts
Labels: feature, frontend

#123 드랍다운 이외의 공간 클릭 시 드랍다운 컴포넌트 제거 구현
  client/src/components/calendar/CalendarView/index.tsx
  client/src/components/calendar/TableCell/index.tsx
  client/src/components/common/Dropdown/index.tsx
  client/src/components/common/Dropdown/styles.ts
  client/src/container/Calendar/index.tsx
Labels: feature, frontend

#132 관리페이지 Item component 구현
  client/src/assets/svg/Minus.svg
  client/src/assets/svg/Pencil.svg
  client/src/components/common/ManageItem/index.stories.tsx
  client/src/components/common/ManageItem/index.tsx
  client/src/components/common/ManageItem/styles.tsx
  client/src/components/common/ManageItem/types.tsx
  client/src/components/common/ManageItemInput/index.stories.tsx
  client/src/components/common/ManageItemInput/index.tsx
  client/src/components/common/ManageItemInput/styles.tsx
  client/src/components/common/ManageItemInput/types.tsx
  client/src/components/common/buttons/CustomButton/index.tsx
  client/src/components/common/buttons/CustomButton/styles.tsx
  client/src/components/common/buttons/CustomButton/types.tsx
  client/src/components/common/forms/CustomInput/index.tsx
  client/src/components/common/forms/CustomInput/types.ts
Labels: feature, frontend

#134 [Feature]드랍다운 버튼 이외 클릭 이벤트 스타일 추가
  client/src/components/common/Dropdown/index.tsx
  client/src/components/common/Dropdown/styles.ts
Labels: feature, frontend

#131 새로운 가계부 등록시 업데이트가 발생하지 않는 문제 수정
  .github/workflows/run-test.yml
  client/config-overrides.js
  client/package.json
  client/src/App.test.tsx
  client/src/commons/types/transaction.ts
  client/src/libs/api/transaction.ts
  client/src/modules/transaction/actions.ts
  client/src/modules/transaction/reducer.test.ts
  client/src/modules/transaction/reducer.ts
  server/package.json
  server/src/domain/transaction/transaction.service.test.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/loader/database.ts
  yarn.lock
Labels: bug

#136 결제수단 관리 레이아웃 구현
  client/src/App.tsx
  client/src/commons/dto/payment-request.ts
  client/src/commons/types/payment.ts
  client/src/components/common/ManageItemInput/index.stories.tsx
  client/src/components/common/ManageItemInput/index.tsx
  client/src/components/common/ManageItemInput/types.tsx
  client/src/components/common/layouts/Header/index.tsx
  client/src/components/manage/ManageHeader/index.stories.tsx
  client/src/components/manage/ManageHeader/index.tsx
  client/src/components/manage/ManageHeader/styles.tsx
  client/src/components/manage/ManageHeader/types.tsx
  client/src/components/manage/ManageItem/index.stories.tsx
  client/src/components/manage/ManageItem/index.tsx
  client/src/components/manage/ManageItem/styles.tsx
  client/src/components/manage/ManageItem/types.tsx
  client/src/components/manage/ManageItemInput/index.stories.tsx
  client/src/components/manage/ManageItemInput/index.tsx
  client/src/components/manage/ManageItemInput/styles.tsx
  client/src/components/manage/ManageItemInput/types.tsx
  client/src/container/PaymentManageMain/index.tsx
  client/src/container/PaymentManageMain/styles.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/libs/api/payment.ts
  client/src/modules/payment/actions.ts
  client/src/modules/payment/reducer.ts
  client/src/modules/payment/types.ts
  client/src/views/PaymentManagePage/index.tsx
  server/src/domain/payment/payment.router.ts
  server/src/domain/payment/payment.service.ts
  server/src/domain/transaction/transaction.router.ts
Labels: feature, frontend

#138 DateUtil 리팩토링 진행
  client/src/GlobalStyled.ts
  client/src/components/common/Dropdown/index.tsx
  client/src/components/common/Dropdown/styles.ts
  client/src/container/Calendar/index.tsx
  client/src/container/DashboardDetails/index.tsx
  client/src/container/SelectMonth/index.tsx
  client/src/libs/api/transaction.ts
  client/src/libs/dateUtils.ts
  client/src/modules/transaction/reducer.test.ts
  yarn.lock
Labels: frontend, refactoring

#142 고정 지출 완료, 예정으로 분리, 회원가입 날짜 상태 관리
  client/src/commons/types/fixedExpenditure.ts
  client/src/components/fixedExpenditure/Item/index.tsx
  client/src/components/fixedExpenditure/Item/styles.ts
  client/src/components/fixedExpenditure/Item/types.ts
  client/src/container/Authorization/index.tsx
  client/src/container/DetailedFixedExpenditure/index.tsx
  client/src/container/DetailedFixedExpenditure/styles.ts
  client/src/container/FixedExpenditure/index.tsx
  client/src/container/FixedExpenditure/styles.ts
  client/src/libs/api/Authorization.ts
  client/src/libs/api/fixedExpenditure.ts
  client/src/modules/authorization/reducer.ts
  client/src/modules/authorization/types.ts
  client/src/modules/fixedExpenditure/actions.ts
  client/src/modules/fixedExpenditure/reducer.ts
  client/src/modules/fixedExpenditure/types.ts
  client/src/views/LoginPage/index.tsx
  server/src/domain/auth/auth.router.ts
  server/src/domain/auth/types/user-dto.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.router.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
  server/src/domain/fixed-expenditure/types.ts
  server/src/entity/user.entity.ts
  server/src/lib/dateUtils.ts
Labels: backend, feature, frontend

#139 결제수단 관리 페이지 기능 구현
  client/src/components/manage/ManageItem/index.tsx
  client/src/components/manage/ManageItem/types.tsx
  client/src/components/manage/ManageItemInput/index.tsx
  client/src/components/manage/ManageItemInput/types.tsx
  client/src/container/PaymentManageMain/index.tsx
  client/src/modules/payment/actions.ts
  client/src/modules/payment/reducer.ts
  client/src/modules/payment/thunks.ts
  server/src/domain/payment/payment.router.ts
  server/src/domain/payment/payment.service.ts
  server/src/entity/payment.entity.ts
Labels: backend, feature, frontend

#146 SMS 결제정보 파싱 구현
  client/.eslintrc.json
  client/src/commons/dto/transaction-request.ts
  client/src/commons/types/transaction.ts
  client/src/components/common/Modal/styles.tsx
  client/src/components/common/forms/CustomInput/index.tsx
  client/src/components/common/forms/CustomInput/types.ts
  client/src/components/manage/ManageItemInput/index.tsx
  client/src/components/transaction/ModalRadioButton/index.tsx
  client/src/components/transaction/ModalRadioButton/types.ts
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionModal/styles.tsx
  client/src/libs/dateUtils.ts
  client/src/libs/smsParser/parser.test.ts
  client/src/libs/smsParser/parser.ts
  client/src/libs/smsParser/types.ts
Labels: feature, frontend

#150 fix: pre-release 버전 이미지 실행 스크립트 수정
  package.json
Labels: bug, chore

#148 고정 지출 버그 수정
  client/src/container/DetailedFixedExpenditure/index.tsx
  client/src/container/FixedExpenditure/index.tsx
  client/src/modules/fixedExpenditure/reducer.ts
  client/src/modules/fixedExpenditure/types.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.router.ts
Labels: backend, bug

#154 사용자의 소비 습관(과소비 지수)을 계산하는 API 구현
  server/jest.config.js
  server/src/domain/aggregate/aggregate.router.ts
  server/src/domain/aggregate/aggregate.service.ts
  server/src/domain/aggregate/agreegate.service.test.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.router.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
  server/src/domain/transaction/transaction.repository.ts
  server/src/domain/transaction/transaction.router.ts
  server/src/domain/transaction/transaction.service.test.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/lib/date-utils/date-utils.test.ts
  server/src/lib/date-utils/index.ts
  server/src/lib/dateUtils.ts
  server/src/seed/seed-generator.ts
  server/src/seed/test.seed.ts
  server/src/seed/up.ts
  server/src/setupTests.ts
Labels: backend, feature

#163 카테고리 통계 API 변경, 카테고리 통계 페이지 구현
  client/package.json
  client/src/App.tsx
  client/src/commons/types/aggregateCategory.ts
  client/src/components/aggregateCategory/Day/index.tsx
  client/src/components/aggregateCategory/Day/styles.tsx
  client/src/components/aggregateCategory/Item/index.tsx
  client/src/components/aggregateCategory/Item/styles.tsx
  client/src/components/aggregateCategory/Main/index.tsx
  client/src/components/aggregateCategory/Main/styles.tsx
  client/src/container/AggregateCategory/index.tsx
  client/src/libs/api/aggregateCategory.ts
  client/src/libs/dateUtils.ts
  client/src/libs/endpoints.ts
  client/src/modules/aggregateCategory/actions.ts
  client/src/modules/aggregateCategory/index.ts
  client/src/modules/aggregateCategory/reducer.ts
  client/src/modules/aggregateCategory/thunks.ts
  client/src/modules/aggregateCategory/types.ts
  client/src/modules/index.ts
  client/src/views/AggregateCategoryPage/index.tsx
  server/src/domain/aggregate/aggregate.router.ts
  server/src/domain/aggregate/aggregate.service.ts
  server/src/domain/aggregate/types.ts
Labels: backend, feature, frontend

#165 date 선택 방법 변경
  client/src/container/Calendar/index.tsx
  client/src/container/Calendar/styles.ts
  client/src/container/SelectMonth/index.tsx
  client/src/container/SelectMonth/styles.tsx
Labels: feature

#166 캘린더 페이지 관련 디자인 수정
  client/src/components/calendar/TableCell/styles.ts
  client/src/components/transaction/AmountText/styles.ts
  client/src/components/transaction/ListItem/index.stories.tsx
  client/src/components/transaction/ListItem/index.tsx
  client/src/components/transaction/ListItem/styles.ts
  client/src/components/transaction/ListItem/types.ts
  client/src/container/Calendar/styles.ts
  client/src/container/TransactionList/index.tsx
  client/src/container/TransactionList/styles.ts
  client/src/container/TransactionSelectList/index.tsx
  client/src/container/TransactionSelectList/styles.ts
Labels: frontend, refactoring

#167 fix: merge 후 오류 발생부분 수정
  client/src/components/common/layouts/Header/index.tsx
  client/src/components/transaction/ListItem/index.tsx
  client/src/components/transaction/ListItem/styles.ts
  client/src/components/transaction/ListItem/types.ts
  client/src/container/DashboardContainer/index.tsx
  yarn.lock
Labels: bug

#169 fix : 공백상태 관리를 위한 EmptyState 컴포넌트 구현
  client/src/components/transaction/EmptyState/index.tsx
  client/src/components/transaction/EmptyState/styles.ts
  client/src/components/transaction/EmptyState/types.ts
  client/src/container/DashboardContainer/index.tsx
  client/src/container/TransactionList/index.tsx
  client/src/container/TransactionSelectList/index.tsx
Labels: enhancement

#170 4주차 버그수정 & 리팩토링 진행
  client/src/components/aggregateCategory/Item/styles.tsx
  client/src/components/common/buttons/ModalToggleButton/styles.tsx
  client/src/components/transaction/EmptyState/index.tsx
  client/src/components/transaction/EmptyState/styles.ts
  client/src/components/transaction/EmptyState/types.ts
  client/src/container/DashboardContainer/index.tsx
  client/src/container/DetailedFixedExpenditure/index.tsx
  client/src/container/SelectMonth/index.tsx
  client/src/container/SelectMonth/styles.tsx
  client/src/container/TransactionList/index.tsx
  client/src/container/TransactionSelectList/index.tsx
  client/src/views/CalendarPage/index.tsx
Labels: bug, refactoring

#171 fix: 월 선택 컴포넌트 위치 수정
  client/src/container/DashboardContainer/styles.ts
  client/src/container/SelectMonth/index.tsx
  client/src/container/SelectMonth/styles.tsx
Labels: bug

#175 달력 일 선택시 거래내역 수정모달 버튼 추가
  client/src/container/TransactionSelectList/index.tsx
Labels: feature, frontend

#177 고정 지출 버그 수정
  client/src/components/fixedExpenditure/Item/index.tsx
  client/src/container/FixedExpenditure/index.tsx
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
Labels: backend, bug, frontend

#178 README.md 업데이트
  README.md
  package.json
  server/.dummy.env
  server/package.json
Labels: chore

#181 fix : 카테고리 관리페이지 버그 수정
  client/src/container/CategoryManageContainer/index.tsx
  client/src/container/CategoryManageMain/index.tsx
Labels: bug, frontend

#183 꺽은선 그래프 통계페이지 구현
  client/src/App.tsx
  client/src/components/transaction/LineGraph/index.tsx
  client/src/components/transaction/LineGraph/styles.tsx
  client/src/components/transaction/LineGraph/types.ts
  client/src/container/DashboardContainer/index.tsx
  client/src/container/LineGraphContainer/index.tsx
  client/src/container/LineGraphContainer/style.tsx
  client/src/container/LineGraphContainer/styles.ts
  client/src/container/LineGraphContainer/types.tsx
  client/src/views/AggregateCategoryPage/index.tsx
  client/src/views/AggregatePeriodPage/index.tsx
Labels: feature, frontend

#190 custom Error 수정
  server/src/common/error.ts
  server/src/common/error/bad-request.ts
  server/src/common/error/database.ts
  server/src/common/error/forbidden.ts
  server/src/common/error/not-found.ts
  server/src/common/error/unauthorized.ts
  server/src/domain/auth/auth.router.ts
  server/src/domain/category/category.service.ts
  server/src/domain/payment/payment.service.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/loader/index.ts
  server/src/middleware/jwt-authorize.ts
Labels: backend, refactoring

#186 카테고리 통계, 라인 차트 페이지 추가 작업, 컴포넌트 화살표 함수로 변경
  client/src/components/aggregateCategory/Main/index.tsx
  client/src/components/aggregateCategory/Main/styles.tsx
  client/src/components/calendar/CalendarView/index.tsx
  client/src/components/calendar/MatrixView/index.tsx
  client/src/components/calendar/TableCell/index.tsx
  client/src/components/category/.gitkeep
  client/src/components/common/ArrowIcon/index.tsx
  client/src/components/common/Dropdown/index.tsx
  client/src/components/common/Logo/index.tsx
  client/src/components/common/Modal/index.tsx
  client/src/components/common/buttons/CustomButton/index.tsx
  client/src/components/common/buttons/ModalToggleButton/index.tsx
  client/src/components/common/buttons/OAuthLoginButton/index.tsx
  client/src/components/common/buttons/OAuthLoginButton/types.ts
  client/src/components/common/forms/CustomSelectInput/index.tsx
  client/src/components/common/layouts/Header/index.tsx
  client/src/components/transaction/AmountText/index.tsx
  client/src/components/transaction/ModalHeaderText/index.tsx
  client/src/components/transaction/ModalRadioButton/index.tsx
  client/src/components/transaction/ModalXButton/index.tsx
  client/src/container/CategoryManageContainer/index.tsx
  client/src/container/DetailedFixedExpenditure/index.tsx
  client/src/container/LineGraphContainer/index.tsx
  client/src/container/PaymentManageMain/index.tsx
Labels: feature, frontend, refactoring

#191 로고 이미지와 헤더, 로그인 페이지 레이아웃 수정
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/assets/svg/Logo.svg
  client/src/components/calendar/CalendarView/index.tsx
  client/src/components/common/layouts/Header/index.tsx
  client/src/components/common/layouts/Header/styles.ts
  client/src/libs/CalendarUtils.ts
  client/src/views/LoginPage/index.tsx
  client/src/views/LoginPage/styles.ts
Labels: frontend, refactoring

#192 fix: DB 변경시 같은 uid를 가진 유저로 로그인 되는 이슈 해결
  README.md
  server/.dummy.env
  server/package.json
  server/src/config/index.ts
  server/src/domain/aggregate/aggregate.service.ts
  server/src/domain/aggregate/agreegate.service.test.ts
  server/src/domain/auth/auth.router.ts
  server/src/domain/auth/types/decoded-jwt.ts
  server/src/domain/auth/utils/jwt-utils.ts
  server/src/domain/user/types/user-dto.ts
  server/src/domain/user/user.service.ts
  server/src/lib/jwt-utils/index.ts
  server/src/lib/jwt-utils/types.ts
  server/src/middleware/jwt-authorize.ts
  server/src/middleware/jwt-authorize/index.ts
  server/src/middleware/jwt-authorize/jwt-authorize-middleware.test.ts
  server/src/seed/test.seed.ts
  yarn.lock
Labels: backend, bug

#187 [fix/calendar] 존재하지 않는 일자 클릭되는 버그 수정
  client/src/components/calendar/TableCell/index.tsx
  client/src/components/calendar/TableCell/styles.ts
  client/src/components/common/forms/CustomSelectInput/index.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionUpdateModal/index.tsx
  client/src/libs/calendarUtils.test.ts
  client/src/libs/calendarUtils.ts
  client/src/libs/checkValidation.ts
  client/src/views/CalendarPage/index.tsx
  client/src/views/DashBoardPage/index.tsx
Labels: bug, frontend

#194 로딩 컴포넌트 추가 및 로그인 체크시 컴포넌트 랜더링되지 않도록 처리
  client/src/App.tsx
  client/src/GlobalStyled.ts
  client/src/assets/svg/Spinner.svg
  client/src/components/common/LoadingSpinner/index.tsx
  client/src/components/common/LoadingSpinner/styles.ts
  client/src/components/common/layouts/MainLayout/index.tsx
  client/src/container/Authorization/index.tsx
  client/src/container/DashboardContainer/index.tsx
  client/src/container/FixedExpenditure/index.tsx
  client/src/container/LineGraphContainer/index.tsx
  client/src/views/AggregateCategoryPage/index.tsx
  client/src/views/AggregatePeriodPage/index.tsx
  client/src/views/CalendarPage/index.tsx
  client/src/views/CategoryManagePage/index.tsx
  client/src/views/DashBoardPage/index.tsx
  client/src/views/DetailedFixedExpenditurePage/index.tsx
  client/src/views/LoginPage/index.tsx
  client/src/views/PaymentManagePage/index.tsx
  client/src/views/layouts/Header/index.stories.tsx
  client/src/views/layouts/Header/index.tsx
  client/src/views/layouts/Header/styles.ts
  client/src/views/layouts/MainLayout/index.tsx
  client/src/views/layouts/MainLayout/styles.ts
  client/src/views/layouts/MainLayout/types.ts
Labels: feature, frontend

#199 카테고리/결제수단 유효성 검사 추가
  client/src/components/common/buttons/CustomButton/index.tsx
  client/src/components/common/buttons/CustomButton/types.tsx
  client/src/components/manage/ManageItemInput/index.tsx
  client/src/components/manage/ManageItemInput/types.tsx
  client/src/container/CategoryManageContainer/index.tsx
  client/src/container/PaymentManageMain/index.tsx
  client/src/libs/checkOverlap.ts
  client/src/libs/checkValidation.ts
Labels: feature, frontend

#201 월 선택시 오른쪽 버튼의 위치가 변경되는 현상 수정
  client/src/App.css
  client/src/App.tsx
  client/src/GlobalStyled.ts
  client/src/container/LineGraphContainer/index.tsx
  client/src/container/SelectMonth/index.tsx
  client/src/container/SelectMonth/styles.tsx
Labels: frontend, refactoring

#205 관리 페이지에서 data 가져오는 로직 추가 및 dispatch 관련 리팩토링
  client/src/container/CategoryManageContainer/index.tsx
  client/src/container/DashboardContainer/index.tsx
  client/src/container/DetailedFixedExpenditure/index.tsx
  client/src/container/FixedExpenditure/index.tsx
  client/src/container/PaymentManageMain/index.tsx
  client/src/container/SelectMonth/index.tsx
  client/src/container/TransactionList/index.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionSelectList/index.tsx
Labels: bug, frontend, refactoring

#208 eslint 오류 수정
  client/src/container/TransactionModal/index.tsx
Labels: bug

#210 프론트엔드 데이터 캐싱 구현
  .github/workflows/run-test.yml
  client/.eslintignore
  client/package.json
  client/src/commons/types/aggregate.ts
  client/src/commons/types/transaction.ts
  client/src/components/aggregateCategory/Day/index.tsx
  client/src/components/aggregateCategory/Item/index.tsx
  client/src/components/aggregateCategory/Main/index.tsx
  client/src/components/common/Dropdown/index.tsx
  client/src/components/common/Dropdown/styles.ts
  client/src/container/AggregateCategory/index.tsx
  client/src/container/Calendar/index.tsx
  client/src/container/DashboardContainer/index.tsx
  client/src/container/SelectMonth/index.tsx
  client/src/libs/api/aggregate.ts
  client/src/libs/api/aggregateCategory.ts
  client/src/libs/api/category.ts
  client/src/libs/api/fixedExpenditure.ts
  client/src/libs/api/payment.ts
  client/src/libs/api/transaction.ts
  client/src/libs/cache/aggregateCategoryCache/aggregateCategoryData.test.ts
  client/src/libs/cache/aggregateCategoryCache/index.ts
  client/src/libs/cache/cacheUtils.ts
  client/src/libs/cache/categoryCache/categoryCache.test.ts
  client/src/libs/cache/categoryCache/index.ts
  client/src/libs/cache/fixedExpenditureCache/fixedExpenditureCache.test.ts
  client/src/libs/cache/fixedExpenditureCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/mostSpendingCategoryCache.test.ts
  client/src/libs/cache/overspendingIndexCache/index.ts
  client/src/libs/cache/overspendingIndexCache/overspendingIndexCache.test.ts
  client/src/libs/cache/paymentCache/index.ts
  client/src/libs/cache/paymentCache/paymentCache.test.ts
  client/src/libs/cache/transactionCache/index.ts
  client/src/libs/cache/transactionCache/transactionCache.test.ts
  client/src/modules/aggregateCategory/actions.ts
  client/src/modules/aggregateCategory/thunks.ts
  client/src/modules/aggregateCategory/types.ts
  client/src/views/layouts/Header/styles.ts
  package.json
  scripts/build.sh
  server/.eslintignore
  server/package.json
  server/src/domain/aggregate/aggregate.router.ts
  server/src/domain/aggregate/aggregate.service.ts
Labels: feature, frontend, refactoring

#211 고정 지출 쿼리 수정
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
  server/src/entity/fixed-expenditure.entity.ts
  server/src/entity/transaction.entity.ts
Labels: backend, refactoring

#212 5주차 v2 배포
  .github/workflows/auto_reviewer.yml
  .github/workflows/deploy.yml
  .github/workflows/pre-release.yml
  .github/workflows/run-test.yml
  client/.eslintignore
  client/package.json
  client/src/commons/types/aggregate.ts
  client/src/commons/types/transaction.ts
  client/src/components/aggregateCategory/Day/index.tsx
  client/src/components/aggregateCategory/Item/index.tsx
  client/src/components/aggregateCategory/Main/index.tsx
  client/src/components/common/Dropdown/index.tsx
  client/src/components/common/Dropdown/styles.ts
  client/src/container/AggregateCategory/index.tsx
  client/src/container/Calendar/index.tsx
  client/src/container/DashboardContainer/index.tsx
  client/src/container/SelectMonth/index.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/libs/api/aggregate.ts
  client/src/libs/api/aggregateCategory.ts
  client/src/libs/api/category.ts
  client/src/libs/api/fixedExpenditure.ts
  client/src/libs/api/payment.ts
  client/src/libs/api/transaction.ts
  client/src/libs/cache/aggregateCategoryCache/aggregateCategoryData.test.ts
  client/src/libs/cache/aggregateCategoryCache/index.ts
  client/src/libs/cache/cacheUtils.ts
  client/src/libs/cache/categoryCache/categoryCache.test.ts
  client/src/libs/cache/categoryCache/index.ts
  client/src/libs/cache/fixedExpenditureCache/fixedExpenditureCache.test.ts
  client/src/libs/cache/fixedExpenditureCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/mostSpendingCategoryCache.test.ts
  client/src/libs/cache/overspendingIndexCache/index.ts
  client/src/libs/cache/overspendingIndexCache/overspendingIndexCache.test.ts
  client/src/libs/cache/paymentCache/index.ts
  client/src/libs/cache/paymentCache/paymentCache.test.ts
  client/src/libs/cache/transactionCache/index.ts
  client/src/libs/cache/transactionCache/transactionCache.test.ts
  client/src/modules/aggregateCategory/actions.ts
  client/src/modules/aggregateCategory/thunks.ts
  client/src/modules/aggregateCategory/types.ts
  client/src/views/layouts/Header/styles.ts
  package.json
  scripts/build.sh
  server/.eslintignore
  server/package.json
  server/src/domain/aggregate/aggregate.router.ts
  server/src/domain/aggregate/aggregate.service.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
  server/src/entity/fixed-expenditure.entity.ts
  server/src/entity/transaction.entity.ts
Labels: deploy

#214 [fix]파서시 유효성 검시가 되지 않던 오류 수정
  client/src/components/calendar/TableCell/styles.ts
  client/src/components/common/buttons/CustomButton/index.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionUpdateModal/index.tsx
  client/src/libs/checkOverlap.ts
  client/src/libs/checkValidation.ts
Labels: feature, frontend

#217 거래내역 리스트 lazy-loading 구현
  client/src/container/Calendar/styles.ts
  client/src/container/DetailedFixedExpenditure/index.tsx
  client/src/container/LineGraphContainer/index.tsx
  client/src/container/TransactionList/index.tsx
  client/src/container/TransactionSelectList/index.tsx
  client/src/container/TransactionUpdateModal/index.tsx
Labels: feature, frontend

#218 캐시의 월별로 관리되는 데이터의 개수를 제한하는 로직 추가
  client/src/commons/endpoints.ts
  client/src/commons/mockData.ts
  client/src/components/common/buttons/OAuthLoginButton/index.tsx
  client/src/container/DashboardContainer/index.tsx
  client/src/container/FixedExpenditure/index.tsx
  client/src/libs/api/Authorization.ts
  client/src/libs/api/aggregate.ts
  client/src/libs/api/category.ts
  client/src/libs/api/fixedExpenditure.ts
  client/src/libs/api/payment.ts
  client/src/libs/api/transaction.ts
  client/src/libs/axios.ts
  client/src/libs/cache/aggregateCategoryCache/aggregateCategoryData.test.ts
  client/src/libs/cache/aggregateCategoryCache/index.ts
  client/src/libs/cache/cacheUtils.test.ts
  client/src/libs/cache/cacheUtils.ts
  client/src/libs/cache/categoryCache/categoryCache.test.ts
  client/src/libs/cache/constant.ts
  client/src/libs/cache/fixedExpenditureCache/fixedExpenditureCache.test.ts
  client/src/libs/cache/fixedExpenditureCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/mostSpendingCategoryCache.test.ts
  client/src/libs/cache/overspendingIndexCache/index.ts
  client/src/libs/cache/overspendingIndexCache/overspendingIndexCache.test.ts
  client/src/libs/cache/paymentCache/paymentCache.test.ts
  client/src/libs/cache/transactionCache/index.ts
  client/src/libs/cache/transactionCache/transactionCache.test.ts
  client/src/modules/transaction/reducer.test.ts
Labels: feature, frontend

#215 캘린더 코드 리팩토링(로직 변경, 성능향상)
  client/src/components/calendar/CalendarView/indes.stories.tsx
  client/src/components/calendar/CalendarView/index.tsx
  client/src/components/calendar/CalendarView/types.ts
  client/src/components/calendar/MatrixView/index.tsx
  client/src/components/calendar/MatrixView/types.ts
  client/src/components/calendar/TableCell/index.tsx
  client/src/components/calendar/TableCell/types.ts
  client/src/components/transaction/AmountText/index.tsx
  client/src/components/transaction/AmountText/styles.ts
  client/src/container/Calendar/index.tsx
  client/src/container/TransactionSelectList/index.tsx
  client/src/libs/api/payment.ts
  client/src/libs/cache/cacheUtils.ts
  client/src/libs/calendarUtils.ts
Labels: enhancement, frontend

#219 react lazy 적용
  client/src/App.tsx
  client/src/components/common/LoadingSpinner/styles.ts
  client/src/container/DashboardContainer/index.tsx
  client/src/container/FixedExpenditure/index.tsx
Labels: feature, frontend

#220 달력 구조 개선
  client/src/GlobalStyled.ts
  client/src/assets/svg/Arrow.svg
  client/src/components/calendar/MatrixView/index.tsx
  client/src/components/calendar/MatrixView/types.ts
  client/src/components/calendar/TableCell/index.tsx
  client/src/components/common/ArrowIcon/index.stories.tsx
  client/src/components/common/ArrowIcon/index.tsx
  client/src/components/common/ArrowIcon/styles.ts
  client/src/components/common/ArrowIcon/types.ts
  client/src/container/Calendar/index.tsx
  client/src/container/DashboardContainer/index.tsx
  client/src/libs/nationalCalendarUtils.ts
Labels: enhancement, frontend

#221 5주차 v3 배포
  client/src/App.tsx
  client/src/GlobalStyled.ts
  client/src/assets/svg/Arrow.svg
  client/src/commons/endpoints.ts
  client/src/commons/mockData.ts
  client/src/components/calendar/CalendarView/indes.stories.tsx
  client/src/components/calendar/CalendarView/index.tsx
  client/src/components/calendar/CalendarView/types.ts
  client/src/components/calendar/MatrixView/index.tsx
  client/src/components/calendar/MatrixView/types.ts
  client/src/components/calendar/TableCell/index.tsx
  client/src/components/calendar/TableCell/styles.ts
  client/src/components/calendar/TableCell/types.ts
  client/src/components/common/ArrowIcon/index.stories.tsx
  client/src/components/common/ArrowIcon/index.tsx
  client/src/components/common/ArrowIcon/styles.ts
  client/src/components/common/ArrowIcon/types.ts
  client/src/components/common/LoadingSpinner/styles.ts
  client/src/components/common/buttons/CustomButton/index.tsx
  client/src/components/common/buttons/OAuthLoginButton/index.tsx
  client/src/components/transaction/AmountText/index.tsx
  client/src/components/transaction/AmountText/styles.ts
  client/src/container/Calendar/index.tsx
  client/src/container/Calendar/styles.ts
  client/src/container/DashboardContainer/index.tsx
  client/src/container/DetailedFixedExpenditure/index.tsx
  client/src/container/FixedExpenditure/index.tsx
  client/src/container/LineGraphContainer/index.tsx
  client/src/container/TransactionList/index.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionSelectList/index.tsx
  client/src/container/TransactionUpdateModal/index.tsx
  client/src/libs/api/Authorization.ts
  client/src/libs/api/aggregate.ts
  client/src/libs/api/category.ts
  client/src/libs/api/fixedExpenditure.ts
  client/src/libs/api/payment.ts
  client/src/libs/api/transaction.ts
  client/src/libs/axios.ts
  client/src/libs/cache/aggregateCategoryCache/aggregateCategoryData.test.ts
  client/src/libs/cache/aggregateCategoryCache/index.ts
  client/src/libs/cache/cacheUtils.test.ts
  client/src/libs/cache/cacheUtils.ts
  client/src/libs/cache/categoryCache/categoryCache.test.ts
  client/src/libs/cache/constant.ts
  client/src/libs/cache/fixedExpenditureCache/fixedExpenditureCache.test.ts
  client/src/libs/cache/fixedExpenditureCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/index.ts
  client/src/libs/cache/mostSpendingCategoryCache/mostSpendingCategoryCache.test.ts
  client/src/libs/cache/overspendingIndexCache/index.ts
  client/src/libs/cache/overspendingIndexCache/overspendingIndexCache.test.ts
  client/src/libs/cache/paymentCache/paymentCache.test.ts
  client/src/libs/cache/transactionCache/index.ts
  client/src/libs/cache/transactionCache/transactionCache.test.ts
  client/src/libs/calendarUtils.ts
  client/src/libs/checkOverlap.ts
  client/src/libs/checkValidation.ts
  client/src/libs/nationalCalendarUtils.ts
  client/src/modules/transaction/reducer.test.ts
Labels: deploy

#224 거래내역, 카테고리 통계 쿼리 최적화
  client/src/commons/types/transaction.ts
  client/src/components/transaction/ListItem/index.stories.tsx
  client/src/components/transaction/ListItem/index.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionUpdateModal/index.tsx
  client/src/libs/api/transaction.ts
  client/src/libs/dateUtils.ts
  client/src/modules/transaction/actions.ts
  client/src/modules/transaction/reducer.ts
  client/src/modules/updateModal/reducer.ts
  server/src/domain/aggregate/aggregate.service.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
  server/src/domain/transaction/transaction.service.test.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/domain/transaction/types.ts
  server/src/lib/date-utils/date-utils.test.ts
  server/src/lib/date-utils/index.ts
  server/src/seed/seed-generator.ts
Labels: backend, frontend, refactoring

#225 데모 로그인 추가
  client/public/socials/demo.png
  client/src/components/common/buttons/TestLoginButton/index.tsx
  client/src/components/common/buttons/TestLoginButton/styles.ts
  client/src/container/LoginButton/index.tsx
  client/src/container/LoginButton/styles.tsx
  server/src/common/error/server-error.ts
  server/src/domain/auth/auth.router.ts
  server/src/domain/category/category.service.ts
  server/src/domain/payment/payment.service.ts
  server/src/domain/transaction/transaction.service.ts
  server/src/domain/user/user.service.ts
Labels: feature, frontend

#228 백엔드 validation 로직을 추가했습니다.
  README.md
  client/src/container/AggregateCategory/index.tsx
  client/src/container/DashboardContainer/index.tsx
  server/src/domain/aggregate/aggregate.router.ts
  server/src/domain/aggregate/aggregate.service.ts
  server/src/domain/category/category.router.ts
  server/src/domain/fixed-expenditure/fixed-expenditure.router.ts
  server/src/domain/payment/payment.router.ts
  server/src/domain/transaction/transaction.router.ts
  server/src/lib/validator/core/index.ts
  server/src/lib/validator/core/validator-core.test.ts
  server/src/loader/index.ts
  server/src/middleware/validator/category/category-validator.test.ts
  server/src/middleware/validator/category/index.ts
  server/src/middleware/validator/index.ts
  server/src/middleware/validator/month-query/index.ts
  server/src/middleware/validator/month-query/month-query-validator.test.ts
  server/src/middleware/validator/payment/index.ts
  server/src/middleware/validator/payment/payment-validator.test.ts
  server/src/middleware/validator/transaction/index.ts
  server/src/middleware/validator/transaction/transaction-validator.test.ts
  server/src/seed/clear.ts
  server/src/seed/seed-generator.ts
  server/src/seed/up.ts
Labels: backend, feature

#231 고정 지출 내역 버그 수정
  server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
Labels: backend, bug

#232 거래내역 날짜 수정시 생기는 오류 해결
  client/src/modules/transaction/reducer.ts
Labels: bug, frontend

#229 트랜잭션 업데이트 모달 버그수정
  client/src/components/transaction/ModalRadioButton/index.tsx
  client/src/container/TransactionModal/index.tsx
  client/src/container/TransactionUpdateModal/index.tsx
Labels: bug, frontend

#233 고정 지출 복합인덱스 컬럼 수정
  server/src/entity/fixed-expenditure.entity.ts
Labels: backend, refactoring

#235 transaction scroll 오류 수정
  client/src/container/TransactionList/index.tsx
Labels: bug
